/**:
  ros__parameters:
    wheel_radius: 0.165 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.116 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 0.498 # between front wheel center and rear wheel center
    wheel_tread: 0.583 # between left wheel center and right wheel center
    front_overhang: 0.21693 # between front wheel center and vehicle front
    rear_overhang: 0.21693 # between rear wheel center and vehicle rear
    left_overhang: 0.058 # between left wheel center and vehicle left
    right_overhang: 0.058 # between right wheel center and vehicle right
    vehicle_height: 2.883
    max_steer_angle: 0.70 # [rad]
